spring:
  application:
    name: consulta-cep
  datasource:
    url: jdbc:h2:mem:pedido-consulta-cep
    driver-class-name: org.h2.Driver
  data:
    jdbc:
      dialect: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
api:
  externa:
    url: http://localhost:8089